# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joystick.ui'
#
# Created: Thu Jul 14 22:10:57 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(354, 450)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.yawLabel = QtGui.QLabel(self.centralwidget)
        self.yawLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yawLabel.setObjectName("yawLabel")
        self.verticalLayout_3.addWidget(self.yawLabel)
        self.yawSlider = QtGui.QSlider(self.centralwidget)
        self.yawSlider.setMinimum(-100)
        self.yawSlider.setMaximum(100)
        self.yawSlider.setSingleStep(10)
        self.yawSlider.setPageStep(25)
        self.yawSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yawSlider.setInvertedAppearance(False)
        self.yawSlider.setInvertedControls(False)
        self.yawSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.yawSlider.setObjectName("yawSlider")
        self.verticalLayout_3.addWidget(self.yawSlider)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.altSlider = QtGui.QSlider(self.centralwidget)
        self.altSlider.setMinimum(-100)
        self.altSlider.setMaximum(100)
        self.altSlider.setSingleStep(10)
        self.altSlider.setPageStep(25)
        self.altSlider.setOrientation(QtCore.Qt.Vertical)
        self.altSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.altSlider.setObjectName("altSlider")
        self.horizontalLayout_3.addWidget(self.altSlider)
        self.altLabel = QtGui.QLabel(self.centralwidget)
        self.altLabel.setObjectName("altLabel")
        self.horizontalLayout_3.addWidget(self.altLabel)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pitchSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitchSlider.sizePolicy().hasHeightForWidth())
        self.pitchSlider.setSizePolicy(sizePolicy)
        self.pitchSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pitchSlider.setMinimum(-100)
        self.pitchSlider.setMaximum(100)
        self.pitchSlider.setSingleStep(10)
        self.pitchSlider.setPageStep(25)
        self.pitchSlider.setOrientation(QtCore.Qt.Vertical)
        self.pitchSlider.setInvertedAppearance(False)
        self.pitchSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.pitchSlider.setObjectName("pitchSlider")
        self.horizontalLayout_3.addWidget(self.pitchSlider)
        self.pitchLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitchLabel.sizePolicy().hasHeightForWidth())
        self.pitchLabel.setSizePolicy(sizePolicy)
        self.pitchLabel.setObjectName("pitchLabel")
        self.horizontalLayout_3.addWidget(self.pitchLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.rollSlider = QtGui.QSlider(self.centralwidget)
        self.rollSlider.setMinimum(-100)
        self.rollSlider.setMaximum(100)
        self.rollSlider.setSingleStep(10)
        self.rollSlider.setPageStep(25)
        self.rollSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rollSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.rollSlider.setTickInterval(25)
        self.rollSlider.setObjectName("rollSlider")
        self.verticalLayout_3.addWidget(self.rollSlider)
        self.rollLabel = QtGui.QLabel(self.centralwidget)
        self.rollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rollLabel.setObjectName("rollLabel")
        self.verticalLayout_3.addWidget(self.rollLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_0 = QtGui.QCheckBox(self.centralwidget)
        self.button_0.setObjectName("button_0")
        self.gridLayout_2.addWidget(self.button_0, 0, 0, 1, 1)
        self.button_1 = QtGui.QCheckBox(self.centralwidget)
        self.button_1.setObjectName("button_1")
        self.gridLayout_2.addWidget(self.button_1, 0, 1, 1, 1)
        self.button_2 = QtGui.QCheckBox(self.centralwidget)
        self.button_2.setObjectName("button_2")
        self.gridLayout_2.addWidget(self.button_2, 1, 0, 1, 1)
        self.button_3 = QtGui.QCheckBox(self.centralwidget)
        self.button_3.setObjectName("button_3")
        self.gridLayout_2.addWidget(self.button_3, 1, 1, 1, 1)
        self.button_4 = QtGui.QCheckBox(self.centralwidget)
        self.button_4.setObjectName("button_4")
        self.gridLayout_2.addWidget(self.button_4, 2, 0, 1, 1)
        self.button_5 = QtGui.QCheckBox(self.centralwidget)
        self.button_5.setObjectName("button_5")
        self.gridLayout_2.addWidget(self.button_5, 2, 1, 1, 1)
        self.button_6 = QtGui.QCheckBox(self.centralwidget)
        self.button_6.setObjectName("button_6")
        self.gridLayout_2.addWidget(self.button_6, 3, 0, 1, 1)
        self.button_7 = QtGui.QCheckBox(self.centralwidget)
        self.button_7.setObjectName("button_7")
        self.gridLayout_2.addWidget(self.button_7, 3, 1, 1, 1)
        self.button_8 = QtGui.QCheckBox(self.centralwidget)
        self.button_8.setObjectName("button_8")
        self.gridLayout_2.addWidget(self.button_8, 4, 0, 1, 1)
        self.button_9 = QtGui.QCheckBox(self.centralwidget)
        self.button_9.setObjectName("button_9")
        self.gridLayout_2.addWidget(self.button_9, 4, 1, 1, 1)
        self.button_10 = QtGui.QCheckBox(self.centralwidget)
        self.button_10.setObjectName("button_10")
        self.gridLayout_2.addWidget(self.button_10, 5, 0, 1, 1)
        self.button_11 = QtGui.QCheckBox(self.centralwidget)
        self.button_11.setObjectName("button_11")
        self.gridLayout_2.addWidget(self.button_11, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 354, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Soft Joystick", None, QtGui.QApplication.UnicodeUTF8))
        self.yawLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Alt", None, QtGui.QApplication.UnicodeUTF8))
        self.altLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.pitchLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.rollLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.button_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.button_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.button_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.button_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.button_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.button_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.button_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.button_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.button_10.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.button_11.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))

